# Generated by Django 3.1.6 on 2021-02-13 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=25, unique=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workingwithcsv.country')),
            ],
        ),
    ]
